const bcrypt = require("bcryptjs");
const User = require("../models/User");
const Venue = require("../models/Venue");
const Review = require("../models/Review");

const seedDatabase = async () => {
  try {
    const userCount = await User.countDocuments();
    if (userCount > 0) {
      console.log("🧹 Clearing collections to re-seed...");
      if (global.dbMode === "memory") {
        global.memoryDb.User = [];
        global.memoryDb.Venue = [];
        global.memoryDb.Review = [];
        global.memoryDb.Booking = [];
      } else {
        await User.deleteMany({});
        await Venue.deleteMany({});
        await Review.deleteMany({});
      }
    }

    console.log("🌱 Seeding real-world VenueHub Businesses...");

    // 1. Create default users
    const saltRounds = 10;
    const adminPassword = bcrypt.hashSync("adminpassword", saltRounds);
    const ownerPassword = bcrypt.hashSync("ownerpassword", saltRounds);
    const customerPassword = bcrypt.hashSync("customerpassword", saltRounds);

    const admin = await User.create({
      name: "Admin Moderator",
      email: "admin@venuehub.com",
      password: adminPassword,
      role: "admin",
    });

    const owner = await User.create({
      name: "Karthik Raja (Owner)",
      email: "owner@venuehub.com",
      password: ownerPassword,
      role: "owner",
    });

    const customer = await User.create({
      name: "Priya Sundar (Customer)",
      email: "customer@venuehub.com",
      password: customerPassword,
      role: "user",
    });

    // Generate next 14 available dates
    const today = new Date();
    const dates = [];
    for (let i = 1; i <= 14; i++) {
      const futureDate = new Date(today);
      futureDate.setDate(today.getDate() + i);
      dates.push(futureDate.toISOString().split("T")[0]);
    }

    // 2. 38 Venues/Businesses Data
    const venuesData = [
      {
        venueName: "Sri Saravana Restaurant",
        category: "Restaurant",
        location: "Arakkonam",
        address: "2, Sathyamoorthy St, opp. abishek hospital, suvalpet, Arakkonam, Tamil Nadu 631001",
        googleMapsLink: "https://maps.app.goo.gl/ckbJhfsD6ZTpRyT17?g_st=ac",
        priceRange: "₹₹",
        openingHours: "07:00 AM - 10:30 PM",
        capacity: 120,
        price: 2500, // table reserve / party package base price
        contactNumber: "9876543200",
        description: "Popular local restaurant in Arakkonam offering premium South Indian meals, delicious Chinese items, and custom special event spaces for family celebrations and dining bookings.",
        images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800"],
        amenities: ["AC Dining Room", "Table Reservation", "Catering", "Parking Area"],
        menu: ["Veg Biryani", "Mutton Biryani", "Special Dosa", "Paneer Butter Masala", "South Indian Meals"],
        tableReservation: true,
        birthdayDecoration: true,
        anniversaryPackages: true,
        familyDining: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.5,
        reviewsCount: 1,
      },
      {
        venueName: "Golden Bliss Massage & Spa",
        category: "Spa & Massage",
        location: "Chennai",
        address: "Check Post Area, Poonamallee High Rd, Chennai, Tamil Nadu 600056",
        googleMapsLink: "https://maps.app.goo.gl/v7qDhBCSPvvMWgEX9?g_st=ac",
        priceRange: "₹₹₹",
        openingHours: "09:00 AM - 08:30 PM",
        capacity: 10,
        price: 1800, // massage starting price
        contactNumber: "9876543201",
        description: "Relaxing massage center on Chennai suburbs with premium spa amenities. Specializes in aromatherapy, deep tissue therapy, herbal steam baths, and holistic wellness procedures.",
        images: ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Private Massage Cabins", "Locker Room", "Scented Oils", "Shower Room"],
        spaServices: ["Facials", "Herbal Wraps", "Steam Therapy"],
        massagePackages: ["Full Body Thai Massage", "Deep Tissue Therapy", "Aromatherapy Massage"],
        steamBath: true,
        appointmentBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.8,
        reviewsCount: 1,
      },
      {
        venueName: "Game Stop Arena",
        category: "Gaming",
        location: "Arakkonam",
        address: "M298, Tamil Nadu Housing Board, Jothi Nagar, Arakkonam, Tamil Nadu 631003",
        googleMapsLink: "https://maps.app.goo.gl/j2aU3Sf16dPf7SWH8?g_st=ac",
        priceRange: "₹",
        openingHours: "10:00 AM - 10:00 PM",
        capacity: 40,
        price: 150, // price per hour
        contactNumber: "9876543202",
        description: "Best gaming lounge in Jothi Nagar, Arakkonam. Features PS5, Xbox Series X consoles, high-end PC rigs, VR headsets, and cozy lounge seating with dynamic lighting.",
        images: ["https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800"],
        amenities: ["High-speed WiFi", "Air Conditioned", "Snack Bar", "Power Backup"],
        gamesAvailable: ["FIFA 25", "GTA V", "Call of Duty: Warzone", "Tekken 8", "Beat Saber VR"],
        pricePerHour: 150,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.6,
        reviewsCount: 1,
      },
      {
        venueName: "Gameplay Urban Square",
        category: "Gaming",
        location: "Chennai",
        address: "3 Katipara, Gameplay, Urban Square, Zone 1B, Ramapuram, Chennai, Tamil Nadu 600016",
        googleMapsLink: "https://maps.app.goo.gl/Ad8pFkTSZzhgCaL98?g_st=ac",
        priceRange: "₹₹",
        openingHours: "09:30 AM - 11:00 PM",
        capacity: 60,
        price: 250,
        contactNumber: "9876543203",
        description: "Premium arcade and virtual reality gaming zone inside Urban Square, Ramapuram. Perfect for kids' birthday celebrations, youth groups, and competitive esports leagues.",
        images: ["https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=800"],
        amenities: ["AC", "Wheelchair Accessible", "Valet Parking", "Food Court Access"],
        gamesAvailable: ["Racing Simulators", "VR Rollercoaster", "Arcade Shooting", "Bowling Alley"],
        pricePerHour: 250,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.7,
        reviewsCount: 0,
      },
      {
        venueName: "Freeing India Escape Rooms",
        category: "Gaming",
        location: "Chennai",
        address: "E21, 16th Cross St, GOCHS Colony, Besant Nagar, Chennai, Tamil Nadu 600090",
        googleMapsLink: "https://maps.app.goo.gl/F38z25Te4AA8FJWW9",
        priceRange: "₹₹₹",
        openingHours: "11:00 AM - 10:00 PM",
        capacity: 25,
        price: 350,
        contactNumber: "9876543204",
        description: "Thrilling physical adventure games where you decode clues and solve puzzles to escape rooms. Located at the scenic Besant Nagar, ideal for team building fests.",
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Locker Storage", "AC Reception", "Photo Stand", "Beverages Bar"],
        gamesAvailable: ["Prison Break", "Lost Temple Mystery", "Zombie Apocalypse Escape", "Alice in Wonderland"],
        pricePerHour: 350,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.9,
        reviewsCount: 0,
      },
      {
        venueName: "Vignesh Party Hall and Lodge",
        category: "Party Hall",
        location: "Arakkonam",
        address: "3MR6+X47, Arakkonam, Tamil Nadu 631003",
        googleMapsLink: "https://maps.app.goo.gl/UcejkjKgSyTRh7xW9?g_st=ac",
        priceRange: "₹₹",
        openingHours: "24 Hours (Booking slot)",
        capacity: 250,
        price: 25000,
        contactNumber: "9876543205",
        description: "Comfortable and budget-friendly party hall in Arakkonam. Features well-appointed guest rooms (lodging), catering space, and basic audio setups.",
        images: ["https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&q=80&w=800"],
        amenities: ["AC Hall", "Stage Setup", "Attached Lodging rooms", "Car Parking"],
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.2,
        reviewsCount: 0,
      },
      {
        venueName: "Sri Balaji Party Hall",
        category: "Party Hall",
        location: "Arakkonam",
        address: "3MW5+995, Thiruthani Rd, Arakkonam, Tamil Nadu 631003",
        googleMapsLink: "https://maps.app.goo.gl/R2fNFAeW7y21V78y5?g_st=ac",
        priceRange: "₹",
        openingHours: "06:00 AM - 10:00 PM",
        capacity: 180,
        price: 15000,
        contactNumber: "9876543206",
        description: "Economical mini function hall located on Thiruthani road. Best suited for birthday celebrations, corporate meetings, and family ceremonies.",
        images: ["https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Stage Decoration Support", "Dining Hall", "Audio Speakers", "Parking Area"],
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.0,
        reviewsCount: 0,
      },
      {
        venueName: "Vijay Palace Marriage Hall",
        category: "Marriage Hall",
        location: "Arakkonam",
        address: "73/2, Kalyana Mandapam St, opp. indhra Gandhi statue, Tamil Nadu Housing Board, stoping, Arakkonam, Tamil Nadu 631003",
        googleMapsLink: "https://maps.app.goo.gl/gw6BJH1xKSPEzHsy7?g_st=ac",
        priceRange: "₹₹₹",
        openingHours: "24 Hours (Event slot)",
        capacity: 800,
        price: 75000,
        contactNumber: "9876543207",
        description: "One of Arakkonam's landmark wedding spaces. Huge seating capacity, grand stage design, separate large buffet area, air-conditioning, and security monitoring.",
        images: ["https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&q=80&w=800"],
        amenities: ["AC Mandapam", "Power Backup", "Bride & Groom Suites", "Valet Parking", "Catering Stage"],
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.7,
        reviewsCount: 0,
      },
      {
        venueName: "Soap Football Mogappair",
        category: "Gaming",
        location: "Chennai",
        address: "PC-5, Bazaar Rd, near MMM Hospital, Mogappair East, Chennai, Tamil Nadu 600037",
        googleMapsLink: "https://maps.app.goo.gl/UBw9zBBVmJq5sd9q8",
        priceRange: "₹₹",
        openingHours: "06:00 AM - 12:00 AM",
        capacity: 30,
        price: 450, // price per hour per head or base rate
        contactNumber: "9876543208",
        description: "Chennai's premier soap football field. Super slip-and-slide soap-filled football arena for friends, parties, and corporate events to celebrate in a fun way.",
        images: ["https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Changing Rooms", "Showers", "Safety Helmets", "Spectator Deck"],
        gamesAvailable: ["Soap Football", "Slippery Volleyball"],
        pricePerHour: 450,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.8,
        reviewsCount: 0,
      },
      {
        venueName: "Turf 73 Sport Arena",
        category: "Gaming",
        location: "Arakkonam",
        address: "No: 395B/2D, Thanigai, Polur, Arakkonam, Tamil Nadu 631003",
        googleMapsLink: "https://maps.app.goo.gl/drDNRACakPgGq66Y8?g_st=ac",
        priceRange: "₹₹",
        openingHours: "05:00 AM - 11:30 PM",
        capacity: 22,
        price: 1000, // booking per hour turf
        contactNumber: "9876543209",
        description: "Top-notch AstroTurf facility for box cricket and 5-a-side football in Arakkonam. Features professional floodlights for night games and equipment rental.",
        images: ["https://images.unsplash.com/photo-1529900748604-07564a03e7a6?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Night Floodlights", "Mineral Water", "Sports Equipment Rent", "Seating Dugouts"],
        gamesAvailable: ["Box Cricket", "5-a-side Football", "Futsal"],
        pricePerHour: 1000,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.6,
        reviewsCount: 0,
      },
      {
        venueName: "JR King's Turf",
        category: "Gaming",
        location: "Arakkonam",
        address: "4M32+F56, Arakkonam, Tamil Nadu 631003",
        googleMapsLink: "https://maps.app.goo.gl/PuHW5ip47p8vwZg39?g_st=ac",
        priceRange: "₹₹",
        openingHours: "06:00 AM - 11:00 PM",
        capacity: 20,
        price: 800,
        contactNumber: "9876543210",
        description: "Excellent multi-sports turf in Arakkonam Outskirts. Very popular among local youths for weekend cricket fests and football practice sessions.",
        images: ["https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Drinking Water", "Dressing Area", "Bats & Ball Rental", "Night Lighting"],
        gamesAvailable: ["Cricket Match", "Football Play Session"],
        pricePerHour: 800,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.4,
        reviewsCount: 0,
      },
      {
        venueName: "Avadi Swimming Center",
        category: "Swimming",
        location: "Avadi",
        address: "Hotel Preithaa Garden Check Post, 140, New Military Rd, Kasturba Nagar, Avadi, Tamil Nadu 600054",
        googleMapsLink: "https://maps.app.goo.gl/ycn9Lyp8CZyGd6vN7?g_st=ac",
        priceRange: "₹₹",
        openingHours: "06:00 AM - 08:00 PM",
        capacity: 50,
        price: 150, // Day pass price
        contactNumber: "9876543211",
        description: "Standard clean swimming pool facility inside Hotel Preithaa Garden, Avadi. Offers monthly swimming classes and affordable hourly day passes for the public.",
        images: ["https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Shower Rooms", "Life Guard", "Coaching Staff", "Locker Facility"],
        adultPool: true,
        kidsPool: true,
        coachAvailable: true,
        monthlyMembership: 1500,
        dayPass: 150,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.5,
        reviewsCount: 0,
      },
      {
        venueName: "Vedha Swimming Pool",
        category: "Swimming",
        location: "Arakkonam",
        address: "Winterpet, Arakkonam, Tamil Nadu 631005",
        googleMapsLink: "https://maps.app.goo.gl/6cUrhv3p5ny4URBL7?g_st=ac",
        priceRange: "₹",
        openingHours: "06:00 AM - 07:00 PM",
        capacity: 35,
        price: 100,
        contactNumber: "9876543212",
        description: "Popular local swimming pool in Winterpet area of Arakkonam. Clean water supply, separate timings for batches, and daily day-passes available.",
        images: ["https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Basic Showers", "Safety Floats", "Spectator Seating", "Parking slots"],
        adultPool: true,
        kidsPool: false,
        coachAvailable: false,
        monthlyMembership: 1000,
        dayPass: 100,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.1,
        reviewsCount: 0,
      },
      {
        venueName: "Zay Hey Fun Trampoline & Pool",
        category: "Swimming",
        location: "Thiruvallur",
        address: "Subhi Tower, PACR Salai, Thiruvallur, Tamil Nadu 602001",
        googleMapsLink: "https://maps.app.goo.gl/9PwLF7pveCvymL8X7?g_st=ac",
        priceRange: "₹₹",
        openingHours: "10:00 AM - 09:00 PM",
        capacity: 45,
        price: 300,
        contactNumber: "9876543213",
        description: "Exciting kids and family entertainment center in Thiruvallur. Combines a trampoline jumping arena with a fun kids splash pool and water activities.",
        images: ["https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Jumping Socks provided", "AC Waiting Lounge", "Kids Splash slides", "Clean Water"],
        adultPool: true,
        kidsPool: true,
        coachAvailable: false,
        monthlyMembership: 2000,
        dayPass: 300,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.6,
        reviewsCount: 0,
      },
      {
        venueName: "Award City Pool Park",
        category: "Swimming",
        location: "Poonamallee",
        address: "Theme Park Highway Rd, Poonamallee, Tamil Nadu 600056",
        googleMapsLink: "https://maps.app.goo.gl/RhaUSB192Fw1uf9j7",
        priceRange: "₹₹₹",
        openingHours: "09:00 AM - 06:00 PM",
        capacity: 80,
        price: 400,
        contactNumber: "9876543214",
        description: "Spacious theme park pool with multi-tiered water depth, water slides, splash buckets, and dedicated coaches for swimming classes.",
        images: ["https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Wave Simulator Pool", "Food Stalls", "Costume Rentals", "Safety Lockers"],
        adultPool: true,
        kidsPool: true,
        coachAvailable: true,
        monthlyMembership: 2500,
        dayPass: 400,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.7,
        reviewsCount: 0,
      },
      {
        venueName: "Athisayam Water Park Pool",
        category: "Swimming",
        location: "Chennai",
        address: "ECR Highway Outskirts, Chennai, Tamil Nadu 600115",
        googleMapsLink: "https://maps.app.goo.gl/7xRkY1uhrQ8dg7aR8?g_st=ac",
        priceRange: "₹₹₹",
        openingHours: "09:30 AM - 06:30 PM",
        capacity: 200,
        price: 500,
        contactNumber: "9876543215",
        description: "Massive water playground featuring giant wave pools, interactive water cascades, multi-lane racing slides, and full family change suites.",
        images: ["https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Giant Wave Generator", "Locker System", "Canteen", "First Aid Room"],
        adultPool: true,
        kidsPool: true,
        coachAvailable: false,
        monthlyMembership: 3000,
        dayPass: 500,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.4,
        reviewsCount: 0,
      },
      {
        venueName: "Highway Grand Theme Pool",
        category: "Swimming",
        location: "Tiruvallur",
        address: "Chennai - Thiruttani - Renigunta Hwy, Tiruvallur, Tamil Nadu 602001",
        googleMapsLink: "https://maps.app.goo.gl/mswxUGC1yHCy6qM16?g_st=ac",
        priceRange: "₹₹",
        openingHours: "10:00 AM - 06:00 PM",
        capacity: 100,
        price: 450,
        contactNumber: "9876543216",
        description: "Excellent water park pool stop located on the Tiruvallur highway. Best spot for families looking for a weekend dive and water activities.",
        images: ["https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Showers", "Restaurant", "Life Vest Rental", "Sun Beds"],
        adultPool: true,
        kidsPool: true,
        coachAvailable: false,
        monthlyMembership: 2200,
        dayPass: 450,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.3,
        reviewsCount: 0,
      },
      {
        venueName: "Black Thunder Water Club",
        category: "Swimming",
        location: "Ambattur",
        address: "Redhills Outskirts Road, Ambattur, Chennai 600053",
        googleMapsLink: "https://maps.app.goo.gl/akboaRnBuuVJmqu7A",
        priceRange: "₹₹₹",
        openingHours: "10:00 AM - 05:30 PM",
        capacity: 150,
        price: 600,
        contactNumber: "9876543217",
        description: "Premium water-themed club near Ambattur. Features standard Olympic-sized training pools, lazy river loops, and dedicated water games sections.",
        images: ["https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Olympic Pool", "Lazy River", "Locker Room", "Refreshment Bar"],
        adultPool: true,
        kidsPool: true,
        coachAvailable: true,
        monthlyMembership: 3500,
        dayPass: 600,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.5,
        reviewsCount: 0,
      },
      {
        venueName: "Queensland Water Resort",
        category: "Swimming",
        location: "Poonamallee",
        address: "Chennai-Bengaluru Highway, Palanjur, Poonamallee, Chennai 600123",
        googleMapsLink: "https://maps.app.goo.gl/vtsxYYZ5S7HtTor26",
        priceRange: "₹₹₹",
        openingHours: "09:30 AM - 05:30 PM",
        capacity: 300,
        price: 550,
        contactNumber: "9876543218",
        description: "Immense water play areas inside Queensland. Has multi-lane dynamic slides, splash lagoons, hot springs simulators, and round-the-clock lifeguards.",
        images: ["https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Locker Rentals", "Fast Food Outlets", "First Aid Desk", "Theme rides"],
        adultPool: true,
        kidsPool: true,
        coachAvailable: false,
        monthlyMembership: 2800,
        dayPass: 550,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.6,
        reviewsCount: 0,
      },
      {
        venueName: "Wonderla Water Arena",
        category: "Swimming",
        location: "Chennai",
        address: "Wonderla Highway Outskirts, ECR Road, Chennai 603110",
        googleMapsLink: "https://maps.app.goo.gl/dTXHRha5zxTigRSK6?g_st=ac",
        priceRange: "₹₹₹₹",
        openingHours: "10:30 AM - 06:00 PM",
        capacity: 500,
        price: 800,
        contactNumber: "9876543219",
        description: "World-class water park featuring state-of-the-art heated pools, massive wave generator machines, high-thrill drop slides, and premium dining options.",
        images: ["https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Wave Pool", "Solar Heated Pool", "Premium Lockers", "Multi-cuisine Restaurant"],
        adultPool: true,
        kidsPool: true,
        coachAvailable: false,
        monthlyMembership: 5000,
        dayPass: 800,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.8,
        reviewsCount: 0,
      },
      {
        venueName: "VGP Aqua Kingdom",
        category: "Swimming",
        location: "Chennai",
        address: "East Coast Road, Injambakkam, Chennai, Tamil Nadu 600115",
        googleMapsLink: "https://maps.app.goo.gl/BLhgDVdZfAvPca9y6?g_st=ac",
        priceRange: "₹₹₹",
        openingHours: "09:30 AM - 06:00 PM",
        capacity: 250,
        price: 500,
        contactNumber: "9876543220",
        description: "Renowned ECR beachside water park. Perfect location with splash slides, massive kids splash pools, wave simulation pools, and private dining cabins.",
        images: ["https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?auto=format&fit=crop&q=80&w=800"],
        amenities: ["ECR Beach access", "Costume rental", "Swimming goggles store", "Safety staff"],
        adultPool: true,
        kidsPool: true,
        coachAvailable: false,
        monthlyMembership: 2500,
        dayPass: 500,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.5,
        reviewsCount: 0,
      },
      {
        venueName: "Eagle Boats & Adventures",
        category: "Swimming",
        location: "Chennai",
        address: "ECR Marina Beach, Injambakkam, Chennai 600115",
        googleMapsLink: "https://maps.app.goo.gl/HgZTJYoS9KPXMddu8?g_st=ac",
        priceRange: "₹₹",
        openingHours: "09:00 AM - 06:00 PM",
        capacity: 30,
        price: 350,
        contactNumber: "9876543221",
        description: "Thrilling ECR water club offering speed boating, sea kayaking, and private boating guides for groups and corporate retreats.",
        images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Boating Docks", "Life Jackets", "Safety Boat", "Showers"],
        adultPool: true,
        kidsPool: false,
        coachAvailable: true,
        monthlyMembership: 1800,
        dayPass: 350,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.4,
        reviewsCount: 0,
      },
      {
        venueName: "VRCC Jet Ski Corner",
        category: "Swimming",
        location: "Chennai",
        address: "Pudukuppam Beachfront, ECR Outskirts, Chennai 600115",
        googleMapsLink: "https://maps.app.goo.gl/bsjzc1py6EHCFtzb9?g_st=ac",
        priceRange: "₹₹₹",
        openingHours: "09:00 AM - 05:00 PM",
        capacity: 15,
        price: 500,
        contactNumber: "9876543222",
        description: "Premium ECR beachfront jet-ski and aqua motor sports rental point. Fully certified instructors and high-speed water jet-skis.",
        images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Instructors", "Safety Goggles", "Jet Ski Helmets", "Beach Lounge"],
        adultPool: true,
        kidsPool: false,
        coachAvailable: true,
        monthlyMembership: 3000,
        dayPass: 500,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.7,
        reviewsCount: 0,
      },
      {
        venueName: "Pichavaram Boating Center",
        category: "Swimming",
        location: "Chennai",
        address: "ECR Outskirts Mangrove Reserve, Chennai 600115",
        googleMapsLink: "https://maps.app.goo.gl/4JttQCDJPxn5xD7k6?g_st=ac",
        priceRange: "₹₹",
        openingHours: "08:30 AM - 05:00 PM",
        capacity: 40,
        price: 200,
        contactNumber: "9876543223",
        description: "Relaxed row-boat and motor-boat touring hub through artificial mangrove estuaries. Learn about local coastal biology while paddling.",
        images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Wood Paddling Boats", "Guided Maps", "Life Vests", "Water Bottles"],
        adultPool: false,
        kidsPool: false,
        coachAvailable: true,
        monthlyMembership: 1200,
        dayPass: 200,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.3,
        reviewsCount: 0,
      },
      {
        venueName: "Poovar River Boating",
        category: "Swimming",
        location: "Chennai",
        address: "Adyar Outskirts Backwater Lake, Chennai 600020",
        googleMapsLink: "https://maps.app.goo.gl/aqfAuoYh7w1SUfpr5?g_st=ac",
        priceRange: "₹₹",
        openingHours: "08:00 AM - 06:00 PM",
        capacity: 25,
        price: 250,
        contactNumber: "9876543224",
        description: "Quiet lake cruising experience on backwater pontoons. Relaxed boat rides through scenic water arches and local flora.",
        images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Pontoon boats", "Cushion Seats", "First Aid Box", "Beverages"],
        adultPool: false,
        kidsPool: false,
        coachAvailable: true,
        monthlyMembership: 1500,
        dayPass: 250,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.5,
        reviewsCount: 0,
      },
      {
        venueName: "ECR Kayaking Point",
        category: "Swimming",
        location: "Chennai",
        address: "ECR Backwater Lake Outskirts, Chennai 600115",
        googleMapsLink: "https://maps.app.goo.gl/Qg7iyEanZ3EpwABE8?g_st=ac",
        priceRange: "₹₹",
        openingHours: "06:00 AM - 06:30 PM",
        capacity: 20,
        price: 300,
        contactNumber: "9876543225",
        description: "Kayaking and canoeing facility inside calm backwater lake of ECR. Rent top-notch single and double kayaks.",
        images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Fiberglass Kayaks", "Double Paddles", "Instruction Guides", "Shower rooms"],
        adultPool: true,
        kidsPool: false,
        coachAvailable: true,
        monthlyMembership: 2000,
        dayPass: 300,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.6,
        reviewsCount: 0,
      },
      {
        venueName: "Vellore Amirthi Activity Hub",
        category: "Gaming",
        location: "Arakkonam",
        address: "Amirthi Forest Rd, Kathalampattu, Arakkonam outskirts 631003",
        googleMapsLink: "https://maps.app.goo.gl/EtjoyTTGBiw1pxfr6",
        priceRange: "₹₹",
        openingHours: "08:00 AM - 05:00 PM",
        capacity: 100,
        price: 120,
        contactNumber: "9876543226",
        description: "Exciting nature walk, animal sightseeing, trekking trails, and adventure climbing structures located on Arakkonam outskirts.",
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Restrooms", "Drinking Water", "Tour Guides", "Tree House Dugout"],
        gamesAvailable: ["Trekking", "Ziplining", "Nature Walk", "Rope Climbing"],
        pricePerHour: 120,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.2,
        reviewsCount: 0,
      },
      {
        venueName: "Kaveri Elephant Park",
        category: "Gaming",
        location: "Avadi",
        address: "Check Post Road Elephant Park, Avadi 600054",
        googleMapsLink: "https://maps.app.goo.gl/cSFv3MQPDV3tftYQ7",
        priceRange: "₹₹",
        openingHours: "09:00 AM - 05:00 PM",
        capacity: 50,
        price: 150,
        contactNumber: "9876543227",
        description: "Experiential recreation area in Avadi outskirts. Offers organic elephant interaction, elephant feeding workshop, and jungle walks.",
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Washrooms", "Shaded Huts", "Photo Spot", "Snack Stall"],
        gamesAvailable: ["Elephant Feeding", "Nature Trail", "Photo Session"],
        pricePerHour: 150,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.4,
        reviewsCount: 0,
      },
      {
        venueName: "Theppakadu Camp Experience",
        category: "Gaming",
        location: "Thiruvallur",
        address: "Theppakadu Camp Rd, Thiruvallur 602001",
        googleMapsLink: "https://maps.app.goo.gl/1bvCWvBDBY6aBmaj7?g_st=ac",
        priceRange: "₹₹",
        openingHours: "08:00 AM - 06:00 PM",
        capacity: 60,
        price: 200,
        contactNumber: "9876543228",
        description: "Exciting nature interactions and camp-fires on Thiruvallur suburbs. Features elephant viewing camps, forest safari, and camp activities.",
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Camp Fire pits", "Tents Area", "Cafeteria", "Guide services"],
        gamesAvailable: ["Elephant Interaction", "Camp Fire", "Jungle Safari"],
        pricePerHour: 200,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.6,
        reviewsCount: 0,
      },
      {
        venueName: "Wayanad Wildlife Activity Center",
        category: "Gaming",
        location: "Thiruvallur",
        address: "Thiruvallur Forest Outskirts, Thiruvallur 602001",
        googleMapsLink: "https://maps.app.goo.gl/nvwn1FQcW6NztcQs9",
        priceRange: "₹₹",
        openingHours: "07:00 AM - 05:00 PM",
        capacity: 80,
        price: 250,
        contactNumber: "9876543229",
        description: "Thrilling nature adventures, jungle safari tours, bird watching, and bamboo rafting activities on Thiruvallur forest border.",
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Safaris Jeeps", "Bamboo Rafts", "AC Waiting Center", "Wildlife Experts"],
        gamesAvailable: ["Bird Watching", "Bamboo Rafting", "Forest Safari"],
        pricePerHour: 250,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.5,
        reviewsCount: 0,
      },
      {
        venueName: "Point Calimere Sanctuary Point",
        category: "Gaming",
        location: "Chennai",
        address: "Kodiakarai Outskirts (ECR branch), Chennai 600115",
        googleMapsLink: "https://maps.app.goo.gl/gqAYdwu4EJcgNrcM8?g_st=ac",
        priceRange: "₹",
        openingHours: "08:00 AM - 05:30 PM",
        capacity: 100,
        price: 100,
        contactNumber: "9876543230",
        description: "Coastal wildlife sanctuary experience. Excellent spot for group bicycle rides, deer sightseeing, and migratory bird watching.",
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Bicycles Rental", "Binoculars rental", "Observation Towers", "Toilets"],
        gamesAvailable: ["Deer Sightseeing", "Lighthouse Climbing", "Biking"],
        pricePerHour: 100,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.2,
        reviewsCount: 0,
      },
      {
        venueName: "Bannerghatta Recreation Hub",
        category: "Gaming",
        location: "Chennai",
        address: "Zoo Outer Circle Rd, Chennai 600045",
        googleMapsLink: "https://maps.app.goo.gl/J1vzYJBc9koUeigs5?g_st=ac",
        priceRange: "₹₹",
        openingHours: "09:00 AM - 05:00 PM",
        capacity: 120,
        price: 300,
        contactNumber: "9876543231",
        description: "Dynamic recreational center features zoo tours, butterfly park walkthroughs, tiger/lion safaris, and kids play areas.",
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["AC buses for Safari", "Restaurant", "Snacks Bar", "Souvenir Shop"],
        gamesAvailable: ["Safari Tour", "Zoo Entry", "Butterfly Park Visit"],
        pricePerHour: 300,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.7,
        reviewsCount: 0,
      },
      {
        venueName: "Sculpture Museum Experience",
        category: "Gaming",
        location: "Chennai",
        address: "Sculpture Rd, Mahabalipuram, Chennai 603104",
        googleMapsLink: "https://maps.app.goo.gl/MGA9HHTz3WD2hMqz7?g_st=ac",
        priceRange: "₹",
        openingHours: "09:00 AM - 06:00 PM",
        capacity: 150,
        price: 80,
        contactNumber: "9876543232",
        description: "Engaging cultural experience. Offers guided historical sculpture tours, stone sculpting workshops, and augmented reality history puzzle game.",
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Sculpting Tools provided", "AR Glasses rental", "AC Galleries", "Audio Guides"],
        gamesAvailable: ["Sculpting Workshop", "Guide Tour", "AR History Game"],
        pricePerHour: 80,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.4,
        reviewsCount: 0,
      },
      {
        venueName: "National Art Gallery Center",
        category: "Gaming",
        location: "Chennai",
        address: "Pantheon Rd, Egmore, Chennai 600008",
        googleMapsLink: "https://maps.app.goo.gl/iHX3B77Vv5wjrnBL9?g_st=ac",
        priceRange: "₹",
        openingHours: "09:30 AM - 05:00 PM",
        capacity: 100,
        price: 90,
        contactNumber: "9876543233",
        description: "Interactive art gallery experience. Features standard art exhibitions, painting workshops, and drawing contests for youngsters.",
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Art Supplies", "WiFi", "AC Lounge", "Snack Counter"],
        gamesAvailable: ["Painting Exhibition", "Art Class", "Creative VR Puzzle"],
        pricePerHour: 90,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.5,
        reviewsCount: 0,
      },
      {
        venueName: "Tanjore Art Gallery Outpost",
        category: "Gaming",
        location: "Chennai",
        address: "Maratha Palace Exhibition Hall, Chennai 600008",
        googleMapsLink: "https://maps.app.goo.gl/r1sheejA8NhQdkv26?g_st=ac",
        priceRange: "₹",
        openingHours: "09:00 AM - 05:30 PM",
        capacity: 80,
        price: 100,
        contactNumber: "9876543234",
        description: "Engage in traditional Tanjore glass paintings. Offers structural painting classes, historic walk tours, and custom gold leafing art workshops.",
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Art Canvas provided", "Instructors", "AC Classrooms", "Water dispenser"],
        gamesAvailable: ["Tanjore Art Class", "Historic Walk", "Puzzles"],
        pricePerHour: 100,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.6,
        reviewsCount: 0,
      },
      {
        venueName: "Kerala Arts & Crafts Hub",
        category: "Gaming",
        location: "Chennai",
        address: "Vellar Craft Street (Chennai Center), Chennai 600115",
        googleMapsLink: "https://maps.app.goo.gl/oy9hTCEVAGHMiKN7A?g_st=ac",
        priceRange: "₹₹",
        openingHours: "10:00 AM - 07:00 PM",
        capacity: 90,
        price: 120,
        contactNumber: "9876543235",
        description: "Hands-on experience center. Participate in pottery crafting, handloom weaving demo, and wood carving classes.",
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Pottery Wheels", "Weaving Looms", "Showroom", "AC Restrooms"],
        gamesAvailable: ["Crafts Workshop", "Handloom Weaving", "Clay Modeling"],
        pricePerHour: 120,
        groupBooking: true,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.5,
        reviewsCount: 0,
      },
      {
        venueName: "Temple Adventures Scuba Club",
        category: "Swimming",
        location: "Chennai",
        address: "Harbour Rd, Pondy Marina (ECR Branch), Chennai 600115",
        googleMapsLink: "https://maps.app.goo.gl/hmGox4JWmJeFiiSP8?g_st=ac",
        priceRange: "₹₹₹₹",
        openingHours: "06:30 AM - 05:00 PM",
        capacity: 25,
        price: 1200, // day pass/single dive starting price
        contactNumber: "9876543236",
        description: "PADI certified scuba diving center. Offers shallow pool training, scuba licensing courses, open ocean dives, and marine conservation fests.",
        images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Diving Gear rental", "Pool Classroom", "Ocean Boat", "Hot Showers"],
        adultPool: true,
        kidsPool: false,
        coachAvailable: true,
        monthlyMembership: 8000,
        dayPass: 1200,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.9,
        reviewsCount: 0,
      },
      {
        venueName: "Sandunes Paradise Beach Adventure",
        category: "Swimming",
        location: "Chennai",
        address: "Pudukuppam Beach Outskirts, Chennai 600115",
        googleMapsLink: "https://maps.app.goo.gl/pGGg9dAXyPj8fzXZ9?g_st=ac",
        priceRange: "₹₹₹",
        openingHours: "08:30 AM - 06:00 PM",
        capacity: 100,
        price: 600,
        contactNumber: "9876543237",
        description: "Exciting beach water park. Features paramotoring, jet ski rides, sea boating, beach volleyball net, and swimming safety staff.",
        images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800"],
        amenities: ["Paramotoring center", "Life Guards", "Changing cabins", "Beachside Cafe"],
        adultPool: true,
        kidsPool: true,
        coachAvailable: true,
        monthlyMembership: 4000,
        dayPass: 600,
        availableDates: [...dates],
        ownerId: owner._id,
        isApproved: true,
        rating: 4.8,
        reviewsCount: 0,
      }
    ];

    const seededVenues = [];
    for (const v of venuesData) {
      const created = await Venue.create(v);
      seededVenues.push(created);
    }
    console.log(`Successfully seeded ${seededVenues.length} Real Businesses.`);

    // 3. Create dummy reviews
    const reviews = [
      {
        userId: customer._id,
        venueId: seededVenues[0]._id, // Sri Saravana Restaurant
        rating: 5,
        comment: "Outstanding South Indian dining experience! The family dining hall is super neat and the table reservation was handled instantly. RecommendVeg Biryani."
      },
      {
        userId: customer._id,
        venueId: seededVenues[1]._id, // Golden Bliss Spa
        rating: 5,
        comment: "Absolute heaven! Best massage package I have ever taken. Extremely professional, clean steam bath, and fully sanitized. Will come again!"
      },
      {
        userId: customer._id,
        venueId: seededVenues[2]._id, // Game Stop
        rating: 5,
        comment: "Best VR gaming setup in Arakkonam at a very cheap price per hour! Clean and well maintained rigs."
      }
    ];

    for (const r of reviews) {
      await Review.create(r);
    }
    console.log("Successfully seeded reviews and calculated averages.");
    console.log("🌱 Database seeding complete!");
  } catch (error) {
    console.error("❌ Error seeding database:", error.message);
  }
};

module.exports = seedDatabase;
